services:
  momentary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    environment:
      DB_URL: "postgresql://postgres:postgres@db:5432/mydb"
      REDIS_URL: "redis://redis:6379"

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - momentary_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - momentary_redis_data:/data

volumes:
  momentary_postgres_data:
  momentary_redis_data:
