"""Rename conversations to chats

Revision ID: 7dace64b373d
Revises: 2f8f5f536edb
Create Date: 2025-05-15 14:55:44.967859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dace64b373d'
down_revision = '2f8f5f536edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DIRECT', 'GROUP', name='chattype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('chat_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.UUID(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'chat_participants', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'chats', ['chat_id'], ['id'])
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('chat_id')

    op.drop_table('chat_participants')
    op.drop_table('chats')
    # ### end Alembic commands ###
