"""Change refresh_token type to str in sessions

Revision ID: 8e870422d001
Revises: fb45b9c70726
Create Date: 2025-05-15 09:54:23.430057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e870422d001'
down_revision = 'fb45b9c70726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###
