"""Add refresh token to session

Revision ID: a0ee8f4be7fe
Revises: 98134205f9bf
Create Date: 2025-05-15 06:50:42.600812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ee8f4be7fe'
down_revision = '98134205f9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refresh_token', sa.UUID(as_uuid=False), nullable=False))
        batch_op.create_unique_constraint(None, ['refresh_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('refresh_token')

    # ### end Alembic commands ###
